### ISSUE TITLE
Can it work on iphone 8 plus?

### ISSUE THREAD

**Issue by Wo-Ki2** [omarmhaimdat/WhoAreYou#1]
Hi, I am interested in the projects, so I have run it without errors.However , the view is just black .So , can you tell me whether it can work on iphone 8 plus without faceID?

**Comment by omarmhaimdat** [comment]
I think that only iPhones with TrueDepth (iPhone X, iPhone Xr, iPhone Xs) can use the Face detection as part of the ARKit. But you can still use the Face detection features that is part of the 'Vision' built-in library.
